services:
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
      target: dev

    volumes:
      - ./front/:/code
      - /code/node_modules
    ports: 
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"

  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./api/:/code
    ports: 
      - 8080:8080

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin